use chomsky_emit::{GaiaEmitter, JvmBackend};
use chomsky_extract::{Backend, IKunTree};
use std::sync::Arc;

#[test]
fn test_gaia_jvm_emit() {
    let emitter = GaiaEmitter::new("jvm").with_backend("jvm", Arc::new(JvmBackend::default()));

    // Create a simple class with a method using extensions
    let tree = IKunTree::Extension(
        "class".to_string(),
        vec![
            IKunTree::StringConstant("HelloWorld".to_string()),
            IKunTree::Seq(vec![IKunTree::Extension(
                "method".to_string(),
                vec![
                    IKunTree::StringConstant("main".to_string()),
                    IKunTree::StringConstant("V".to_string()),
                    IKunTree::Seq(vec![
                        IKunTree::Extension(
                            "getstatic".to_string(),
                            vec![
                                IKunTree::StringConstant("java/lang/System".to_string()),
                                IKunTree::StringConstant("out".to_string()),
                            ],
                        ),
                        IKunTree::Extension(
                            "ldc".to_string(),
                            vec![IKunTree::StringConstant("Hello from Gaia!".to_string())],
                        ),
                        IKunTree::Extension(
                            "invokevirtual".to_string(),
                            vec![
                                IKunTree::StringConstant("java/io/PrintStream".to_string()),
                                IKunTree::StringConstant("println".to_string()),
                            ],
                        ),
                    ]),
                ],
            )]),
        ],
    );

    let result = emitter
        .generate(&tree)
        .expect("Failed to generate JVM bytecode");

    match result {
        chomsky_extract::BackendArtifact::Binary(bytes) => {
            assert!(!bytes.is_empty(), "Generated bytecode should not be empty");
            // Basic check for Java class file magic number
            assert_eq!(&bytes[0..4], &[0xCA, 0xFE, 0xBA, 0xBE]);
        }
        _ => panic!("Expected Binary artifact"),
    }
}
